# Generated by Django 5.2.7 on 2025-10-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscibers',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Bin+', 'Bin+'), ('Bin_premium', 'Bin_premium')], default='Basic', max_length=20),
        ),
    ]
