# Generated by Django 5.2.7 on 2025-10-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_alter_user_subscibers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_user',
        ),
        migrations.AddField(
            model_name='user',
            name='your_tag',
            field=models.CharField(blank=True, default=models.CharField(max_length=50, unique=True), max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
