# Generated by Django 5.2.7 on 2026-01-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='login.png', null=True, upload_to='users/'),
        ),
    ]
