# Generated by Django 5.2.7 on 2025-10-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_remove_user_role_user_user_your_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, help_text='Email or phone number', max_length=254, null=True, unique=True),
        ),
    ]
