# Generated by Django 5.2.7 on 2025-10-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='login.png', null=True, upload_to='users/'),
        ),
    ]
