# Generated by Django 5.2.7 on 2026-01-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_message_edited_at_message_original_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
