# Generated by Django 5.2.7 on 2025-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
