# Generated by Django 5.2.7 on 2026-01-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_message_edited_timestamp_message_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_birthday',
            field=models.BooleanField(default=True),
        ),
    ]
