# Generated by Django 5.2.7 on 2025-10-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_alter_user_birthday_alter_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline+', 'Offline+')], default='Online', max_length=20),
        ),
    ]
