# Generated by Django 5.2.7 on 2025-10-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0008_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('Українська', 'українська'), ('English', 'english')], default='English', max_length=20),
        ),
    ]
