# Generated by Django 5.2.7 on 2025-10-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='your_tag',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
