# Generated by Django 5.2.7 on 2025-10-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0010_alter_user_status_alter_user_your_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Moderator', 'Moderator'), ('Administrator', 'Administrator')], default='User', max_length=20),
        ),
    ]
