# Generated by Django 5.2.7 on 2025-10-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0011_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='subscibers',
            new_name='subscribe',
        ),
    ]
