# Generated by Django 5.2.7 on 2025-10-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0012_rename_subscibers_user_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD $'), ('UAH', 'UAH ₴')], default='USD', max_length=10),
        ),
    ]
