# Generated by Django 5.2.7 on 2025-11-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0016_remove_user_gmail_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
