# Generated by Django 5.2.7 on 2025-11-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0017_user_subscribe_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
