# Generated by Django 5.2.7 on 2025-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0018_user_subscription_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
