# Generated by Django 5.2.7 on 2025-11-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0019_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_purchase_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
