# Generated by Django 5.2.7 on 2025-11-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0020_user_subscription_purchase_time_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/backgrounds/'),
        ),
    ]
