# Generated by Django 5.2.7 on 2025-11-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0022_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_purchase_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('UAH', 'UAH')], default='USD', max_length=3, null=True),
        ),
    ]
