# Generated by Django 5.2.7 on 2025-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0023_user_subscription_purchase_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
