# Generated by Django 5.2.7 on 2025-11-17 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0027_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='emailverificationcode',
            table='email_verification_codes',
        ),
    ]
