# Generated by Django 5.2.7 on 2025-11-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0031_message_file_message_file_name_message_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(),
        ),
    ]
