# Generated by Django 5.2.7 on 2025-12-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0033_message_file_message_file_name_message_file_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.AddField(
            model_name='message',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
