# Generated by Django 5.2.7 on 2025-12-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0034_remove_message_file_message_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_path',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
