# Generated by Django 5.2.7 on 2025-12-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0035_remove_message_file_path_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Bin+', 'Bin+'), ('Bin premium', 'Bin premium')], default='Basic', max_length=20),
        ),
    ]
