# Generated by Django 5.2.7 on 2025-12-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0037_alter_user_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Bin+', 'Bin+'), ('Binpremium', 'Binpremium')], default='Basic', max_length=20),
        ),
    ]
