# Generated by Django 5.2.7 on 2025-12-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0039_alter_user_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Moderator', 'Moderator'), ('Administrator', 'Administrator'), ('System Bot', 'System Bot')], default='User', max_length=20),
        ),
    ]
