# Generated by Django 5.2.7 on 2025-12-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0041_stickerpack_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purchased_stickers',
            field=models.ManyToManyField(blank=True, related_name='owners', to='social_network.stickerpack'),
        ),
    ]
