# Generated by Django 5.2.7 on 2025-12-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0042_user_purchased_stickers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='purchased_stickers',
        ),
        migrations.DeleteModel(
            name='Sticker',
        ),
        migrations.DeleteModel(
            name='StickerPack',
        ),
    ]
