# Generated by Django 5.2.7 on 2025-12-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0043_remove_user_purchased_stickers_delete_sticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='backgrounds/'),
        ),
    ]
