# Generated by Django 5.2.7 on 2026-01-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0044_alter_user_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_button_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
