# Generated by Django 5.2.7 on 2026-01-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0045_user_custom_button_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_option',
            field=models.CharField(default='1', max_length=4),
        ),
    ]
