# Generated by Django 5.2.7 on 2026-01-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0046_user_custom_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color_text_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
