# Generated by Django 5.2.7 on 2026-01-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0047_user_color_text_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='color_text_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='color_text_button',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
