# Generated by Django 5.2.7 on 2026-01-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0048_remove_user_color_text_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color_text_button',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black')], default='white', max_length=10),
        ),
    ]
