# Generated by Django 5.2.7 on 2026-01-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0049_alter_user_color_text_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_option',
            field=models.CharField(choices=[('1', 'Light-Dark'), ('2', 'Rainbow'), ('3', 'Bright'), ('4', 'Dark')], default='1', max_length=1),
        ),
    ]
