# Generated by Django 5.2.7 on 2026-01-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0050_alter_user_custom_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color_text_button',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White')], default='black', max_length=10),
        ),
    ]
