# Generated by Django 5.2.7 on 2026-01-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0051_alter_user_color_text_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Bin+', 'Bin+'), ('Bin_premium', 'Bin_premium')], default='Basic', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=50),
        ),
    ]
