# Generated by Django 5.2.7 on 2026-01-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0052_alter_user_subscribe_alter_user_subscribe_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='your_tag',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
